---
title: "Regression Project"
author: "Fiona Dunn"
date: "6/22/2020"
output: html_document
---

```{r}
library("tidyverse")
tennis <- tennis_2013_2017_GS
tennis <- as_tibble(tennis)
```

```{r}
tennis_data_cleaned <- tennis_2013_2017_GS %>% 
  select(-c("w_n_netpt_w", "w_n_netpt", "slam", "player1", "player2", "a1", "a2", "match_id.y")) %>% 
  rename(Net_points = l_n_netpt,
         Net_points_won = l_n_netpt_w) %>% 
  mutate(w_bp_success = w_n_bp_w/w_n_bp,
         l_bp_success = l_n_bp_w/l_n_bp,
         w_sv_success = w_n_sv_w/w_n_sv,
         l_sv_success = l_n_sv_w/l_n_sv,
         upset_bool = ifelse(winner_rank >loser_rank, TRUE, FALSE)) %>% 
  filter(Retirement == FALSE) %>% 
  filter(w_setswon %in% c(2,3))
```

EDA Histogram
```{r}
tennis_data_cleaned %>%
  filter(w_pointswon > 50 & w_pointswon < 200) %>%
  ggplot(aes(x = w_pointswon)) +
  geom_histogram(color = "black", 
                 fill = "darkblue",
                 alpha = 0.3) +
  theme_bw()
```


Scatter plots for EDA
```{r}
##Points Won for Winners v Winner Number Serves Won
tennis_data_cleaned %>%
  ggplot(aes(x = w_n_sv_w,
             y = w_pointswon)) +
  geom_point() +
  geom_smooth()

cor(tennis_data_cleaned$w_pointswon, tennis_data_cleaned$w_n_sv_w)

##Points Won for Winners v w_n_sv
tennis_data_cleaned %>%
  ggplot(aes(x = w_n_sv,
             y = w_pointswon)) +
  geom_point() +
  geom_smooth()

cor(tennis_data_cleaned$w_pointswon, tennis_data_cleaned$w_n_sv)

##Points Won for Winners v l_n_sv_w
tennis_data_cleaned %>%
  ggplot(aes(x = l_n_sv_w,
             y = w_pointswon)) +
  geom_point() +
  geom_smooth()

cor(tennis_data_cleaned$w_pointswon, tennis_data_cleaned$l_n_sv_w)

##Points Won for Winners v l_n_ue
tennis_data_cleaned %>%
  ggplot(aes(x = l_n_ue,
             y = w_pointswon)) +
  geom_point() +
  geom_smooth()

cor(tennis_data_cleaned$w_pointswon, tennis_data_cleaned$l_n_ue)


##Points Won for Winners v l_n_sv
tennis_data_cleaned %>%
  ggplot(aes(x = l_n_sv,
             y = w_pointswon)) +
  geom_point() +
  geom_smooth()

cor(tennis_data_cleaned$w_pointswon, tennis_data_cleaned$l_n_sv)

```


Just a sample lm to practice but does have decently strong correlation
```{r}

idea1 <- lm(w_n_winners ~ w_n_sv + l_n_ue, data = tennis_data_cleaned)

summary(idea1)

library(car)
vif(idea1)
```


checking normality
```{r}
library(ggfortify)
autoplot(idea1) +
  theme_bw()
```

training data practice. plot looks a little hectic...
```{r}
train_preds_1 <- predict(idea1)
train_preds_1

## also equal to 
idea1$fitted.values


tennis_data_cleaned %>%
  tibble(x = (l_n_sv + l_n_ue), y = l_n_winners,
       preds = train_preds_1) %>%
  ggplot(aes((l_n_sv + l_n_ue))) + 
  geom_point(aes(y = l_n_winners)) + 
  geom_point(aes(y = preds),
             color = "red") +
  geom_smooth(aes(y = preds),
            linetype = "dashed",
            color = "blue") +
  theme_bw()
```

another general plot, not incredibly useful 
```{r}
tennis_data_cleaned %>%
  tibble(x = (l_n_sv + l_n_ue), y = l_n_winners) %>%
  ggplot(aes(x, y)) + 
  geom_point() + 
  stat_smooth(method = "lm") +
  theme_bw()


var(predict(idea1)) / var(tennis_data_cleaned$l_n_winners)
```


VARIABLE SELECTION
```{r}
library(ggcorrplot)
tennis_model_data <- tennis_data_cleaned %>%
  dplyr::select(w_n_winners, 
                l_n_sv_w,
                w_n_sv_w,
                w_pointswon,
                w_n_ue,
                l_n_ue,
                w_n_sv,
                l_n_sv)
tennis_cor_matrix <- cor(tennis_model_data)
ggcorrplot(tennis_cor_matrix)


round_cor_matrix <- 
  round(cor(tennis_model_data), 2)
ggcorrplot(round_cor_matrix, 
           hc.order = TRUE,
           type = "lower",
           lab = TRUE)
```


clustering using matrix (using w_n_winners as y)
```{r}

tennis_ex_vars <- dplyr::select(tennis_model_data, -w_pointswon)

exp_cor_matrix <- cor(tennis_ex_vars)

cor_dist_matrix <- 1 - abs(exp_cor_matrix)
cor_dist_matrix <- as.dist(cor_dist_matrix)

library(ggdendro)
tennis_exp_hc <- hclust(cor_dist_matrix,
                     "complete") 
ggdendrogram(tennis_exp_hc,
             rotate = TRUE,
             size = 2)
             
library(dendextend)
cor_dist_matrix %>%
  hclust() %>%
  as.dendrogram() %>%
  set("branches_k_col", 
      k = 2) %>% 
  set("labels_cex", .9) %>%
  ggplot(horiz = TRUE)
  
```

Pairs Plot
```{r}
library(GGally)
tennis_data_linear <- tennis_data_cleaned %>% 
  filter((w_pointswon > 50) & (w_pointswon < 200))

ggpairs(tennis_data_linear,
        columns =
          c("w_n_ue", "l_n_ue", "w_n_winners", "w_n_sv_w", "w_gameswon"),
        mapping = aes(alpha = 0.2)) +
  theme_bw()
```

Creating a linear model 
```{r}
init_w_pointswon <- lm(w_pointswon ~ w_n_winners + w_n_ue + l_n_ue + w_gameswon, tennis_data_linear)
summary(init_w_pointswon)

library(car)
vif(init_w_pointswon)
## w_n_winners and w_gameswon are nearing five

```

Training data
```{r}
train_preds <- predict(init_w_pointswon)
train_preds

tennis_data_linear %>%
  tibble(x = (w_n_winners + w_n_ue + l_n_ue + w_gameswon), y = w_pointswon,
       preds = predict(init_w_pointswon)) %>%
  ggplot(aes(x)) + 
  geom_point(aes(y = w_pointswon)) + 
  geom_point(aes(y = preds),
             color = "red") +
  theme_bw()
```

